services:
  wg-easy:
    build:
      dockerfile: ./Dockerfile.dev
    command: pnpm run dev
    volumes:
      - ./src/:/app/
      - temp:/app/.nuxt/
      - temp1:/app/node_modules/
      # - ./data/:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PASSWORD_HASH=$$2y$$10$$Vhi2tF1i2c/ReW3LdLOru.z7LDITqBgb2wrSVw6sa.KEtbpYgSAf2 # foobar123
      - WG_HOST=192.168.1.233

# folders should be generated inside container
volumes:
  temp:
    driver: local
  temp1:
    driver: local
