name: Lint

on:
  push:
    branches:
      - master
      - production
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wg-easy'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          check-latest: true
          cache: "pnpm"

      - name: pnpm lint
        run: |
          cd src
          pnpm install
          pnpm lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wg-easy'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          check-latest: true
          cache: "pnpm"

      - name: pnpm typecheck
        run: |
          cd src
          pnpm install
          pnpm typecheck

  formatcheck:
    name: Check format
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wg-easy'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          check-latest: true
          cache: "pnpm"

      - name: pnpm format:check
        run: |
          cd src
          pnpm install
          pnpm format:check
